### ISSUE TITLE
Hodnocení úkolu #2

### ISSUE THREAD

**Issue by tommander** [evahrad/PROJEKT-Vizitka#1]
<p>Vizitka se hezky centruje, mezery až na jednu výjimku jsou správně nastavené, písmo i barvy vypadají dobře :) Směle bych si ovšem opět dovolil pár poznámek:</p>
<ol>
  <li>Nemáš u tohoto repozitáře zapnuté Github Pages, takže se nedá vizitka hned zobrazit.</li>
  <li><kbd>index.html</kbd> řádky 10 a 11 &mdash; značky <code>&lt;link&gt;</code> by měly být uvnitř <code>&lt;head&gt;</code>.</li>
  <li>Mezera mezi nadpisem a horní hranou boxu vizitky je příliš velká. Podle toho, co vidím ve <kbd>style.css</kbd> na řádcích 38&ndash;41 to vypadá, že jsi to zkoušela opravit vynulováním <code>margin</code>, ale tam bude problém v jiném prvku, který si tam vyhrazuje místo.</li>
  <li>Při najetí myší na spodní odkazy (Twitter, Facebook) se nemění jejich barva.</li>
</ol>
<p>Tak prosím o zapracování, případně se kdykoliv ptej :) Děkuji.</p>

**Comment by evahrad** [comment]
pages zapnula, písma jsem posunula,
ale u rámečku nevidím mezeru navíc, a když se kouknu na odkazy dole, tak se mi barvy mění
nevím co měnit když nevidím problém

**Comment by tommander** [comment]
<p>Vše OK, dobrá práce :) 👍 </p>
